import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Textarea from "@/components/textarea";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [subject, setSubject] = useState("");
  const [targetAudience, setTargetAudience] = useState("");
  const [keywords, setKeywords] = useState("");
  const [personalNotes, setPersonalNotes] = useState("");
  const [apiResponse, setApiResponse] = useState("");

  const sendInputsToAPI = async () => {
    try {
      const response = await fetch(
        "https://prod.api.promptchainer.io/api/flows/run/clhgojgv60001u70hdt80bx0d",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            variables: {
              subject,
              keywords,
              targetAudience,
              personalNotes,
            },
            apiKey: "4b67a848-ab83-48b4-b8f3-de6ba41d92e9",
          }),
        }
      );

      if (response.ok) {
        const data = await response.json();
        setApiResponse(data[0].output);
      } else {
        throw new Error("Something went wrong with the API call");
      }
    } catch (error) {
      console.error("Error:", error);
    }
  };

  const subjectChange = (e) => {
    setSubject(e.target.value);
  };

  const targetAudienceChange = (e) => {
    setTargetAudience(e.target.value);
  };

  const keywordsChange = (e) => {
    setKeywords(e.target.value);
  };

  const personalNotesChange = (e) => {
    setPersonalNotes(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.left}>
          <Textarea
            placeholder="Start typing, fear not!"
            value={subject}
            onChange={subjectChange}
            label="Subject"
            description="What would you like the article to be about? It can be more than one word."
          />
          <Textarea
            placeholder="Start typing, fear not!"
            value={keywords}
            onChange={keywordsChange}
            label="Keywords"
            description="What would you like the content to include? It can be anything!"
          />
          {/* <div className={styles.keywords}>
            {keywords &&
              keywords.split(",").map((keyword) => {
                return (
                  <p key={keyword.trim()} className={styles.keyword}>
                    {keyword}
                  </p>
                );
              })}
          </div> */}
          <Textarea
            placeholder="Start typing, fear not!"
            value={targetAudience}
            onChange={targetAudienceChange}
            label="Target Audience"
            description="Who's your target audience? For example: purple looking people, breaking up bfs, etc."
          />
          <Textarea
            placeholder="Start typing, fear not!"
            value={personalNotes}
            onChange={personalNotesChange}
            label="Personal Notes"
            description="Any personal notes or additional instructions."
          />

          <button className={styles.button} onClick={sendInputsToAPI}>
            Generate
          </button>
        </div>
        <div className={styles.right}>
          <div className={styles.nav}>
            <h1>
              Content<span>Gen</span>
            </h1>
          </div>
          <div className={styles.title}>
            Bla bla bla is the meaning of life. What is the point of falling in
            love?
          </div>
          <div className={styles.content}>{apiResponse}</div>
        </div>
      </main>
    </>
  );
}
